table 'DataCoSupplyChain Dataset'
	lineageTag: 512f1f8c-3cc5-4a4b-81a9-85d074601f60

	measure 'Total Orders' =
			
			DISTINCTCOUNT('DataCoSupplyChain Dataset'[Order Id])
		formatString: 0
		lineageTag: 7480f9c1-f454-451b-8513-95546f166776

	measure 'Non-Cancelled Orders' =
			
			CALCULATE(
			    [Total Orders],
			    KEEPFILTERS(
			        'DataCoSupplyChain Dataset'[Delivery Status] <> "Shipping canceled"
			    )
			)
		formatString: 0
		lineageTag: 91d951cf-31e6-426e-ac6f-54e284cc38b0

	measure 'Late Orders' =
			
			CALCULATE(
			    [Total Orders],
			    KEEPFILTERS(
			        'DataCoSupplyChain Dataset'[Delivery Status] = "Late delivery"
			    )
			)
		formatString: 0
		lineageTag: fdce7bdc-d5d1-476f-ab83-dc5eb05c31e1

	measure 'Late Delivery Rate' =
			
			DIVIDE(
			    [Late Orders],
			    [Non-Cancelled Orders]
			)
		lineageTag: b60a893a-cad3-48dc-8f2b-24b7164e3cf1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Actual Days' =
			
			CALCULATE(
			    AVERAGEX(
			        VALUES('DataCoSupplyChain Dataset'[Order Id]),
			        CALCULATE(
			            MAX('DataCoSupplyChain Dataset'[Days for shipping (real)])
			        )
			    ),
			    KEEPFILTERS(
			        'DataCoSupplyChain Dataset'[Delivery Status] <> "Shipping canceled"
			    )
			)
		lineageTag: 6e5735e2-d08a-4096-9817-7a0df2303dd6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Scheduled Days' =
			
			CALCULATE(
			    AVERAGEX(
			        VALUES('DataCoSupplyChain Dataset'[Order Id]),
			        CALCULATE(
			            MAX('DataCoSupplyChain Dataset'[Days for shipment (scheduled)])
			        )
			    ),
			    KEEPFILTERS(
			        'DataCoSupplyChain Dataset'[Delivery Status] <> "Shipping canceled"
			    )
			)
		lineageTag: e535dd33-8b97-4fdd-baaa-7b5692b581a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cancelled Orders' =
			
			CALCULATE(
			    [Total Orders],
			    KEEPFILTERS(
			        'DataCoSupplyChain Dataset'[Delivery Status] = "Shipping canceled"
			    )
			)
		formatString: 0
		lineageTag: e83d16a7-fc5a-4b1b-8fdd-b7f6fddbdaa6

	measure 'Net Sales' =
			
			SUM('DataCoSupplyChain Dataset'[Order Item Total])
		lineageTag: 1101a631-3993-497b-bcae-7b9b6860c0bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Recorded Profit' =
			
			SUM('DataCoSupplyChain Dataset'[Order Profit Per Order])
		lineageTag: c72574b8-0285-4519-98a3-4b22de3d6113

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Margin' =
			
			DIVIDE(
			    [Total Recorded Profit],
			    [Net Sales]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: eba103b2-8f85-44d6-9a2e-b90bfa8044e2

	measure 'Average Order Value' =
			
			DIVIDE(
			    [Net Sales],
			    [Total Orders]
			)
		lineageTag: f410fed6-3acd-4561-bc4e-454ffcd66e60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Recorded Loss Amount' =
			
			VAR LossTotal =
			    CALCULATE(
			        SUM('DataCoSupplyChain Dataset'[Order Profit Per Order]),
			        KEEPFILTERS(
			            'DataCoSupplyChain Dataset'[Order Profit Per Order] < 0
			        )
			    )
			RETURN
			    -COALESCE(LossTotal, 0)
		lineageTag: 89cae87d-c56a-4ae6-bac1-138b20b60325

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Loss-Making Items' =
			
			CALCULATE(
			    COUNTROWS('DataCoSupplyChain Dataset'),
			    KEEPFILTERS(
			        'DataCoSupplyChain Dataset'[Order Profit Per Order] < 0
			    )
			)
		formatString: 0
		lineageTag: fc6bac68-3278-4874-a3db-a545649c63fc

	measure 'Markets Served' =
			
			DISTINCTCOUNT('DataCoSupplyChain Dataset'[Market])
		formatString: 0
		lineageTag: a1c3c072-8ba1-40ad-af76-9c05c68269c9

	measure 'Regions Served' =
			
			DISTINCTCOUNT('DataCoSupplyChain Dataset'[Order Region])
		formatString: 0
		lineageTag: 8341e33f-98cd-404b-b680-e34b385f80df

	measure 'Sales Associated with Late Orders' =
			
			CALCULATE(
			    [Net Sales],
			    KEEPFILTERS(
			        'DataCoSupplyChain Dataset'[Delivery Status] = "Late delivery"
			    )
			)
		lineageTag: 07c9d382-cd3a-4782-bec2-fa0d17c757e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Type
		dataType: string
		lineageTag: e1b96b8c-6793-4bd8-9549-13ee50403e1f
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column 'Days for shipping (real)'
		dataType: int64
		formatString: 0
		lineageTag: f4e40ab3-c1d2-48ae-a6a5-2bf07b51ce42
		summarizeBy: sum
		sourceColumn: Days for shipping (real)

		annotation SummarizationSetBy = Automatic

	column 'Days for shipment (scheduled)'
		dataType: int64
		formatString: 0
		lineageTag: 842b72c1-dc2f-4b38-886d-9f571007166b
		summarizeBy: sum
		sourceColumn: Days for shipment (scheduled)

		annotation SummarizationSetBy = Automatic

	column 'Benefit per order'
		dataType: double
		lineageTag: c181de1e-dfc1-484e-9b5d-e98d804708a2
		summarizeBy: sum
		sourceColumn: Benefit per order

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales per customer'
		dataType: double
		lineageTag: c7513bb8-7713-4da4-a3ee-48ee6d3456eb
		summarizeBy: sum
		sourceColumn: Sales per customer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Delivery Status'
		dataType: string
		lineageTag: 19364389-10fe-4fa3-91af-356bd1f08381
		summarizeBy: none
		sourceColumn: Delivery Status

		annotation SummarizationSetBy = Automatic

	column Late_delivery_risk
		dataType: int64
		formatString: 0
		lineageTag: 74c3463d-e128-4dbf-be85-c9308eb1a675
		summarizeBy: sum
		sourceColumn: Late_delivery_risk

		annotation SummarizationSetBy = Automatic

	column 'Category Id'
		dataType: int64
		formatString: 0
		lineageTag: e215422d-59bf-4632-8d02-bf315c067661
		summarizeBy: count
		sourceColumn: Category Id

		annotation SummarizationSetBy = Automatic

	column 'Category Name'
		dataType: string
		lineageTag: db260afc-977c-4828-a70b-62961be9c0cd
		summarizeBy: none
		sourceColumn: Category Name

		annotation SummarizationSetBy = Automatic

	column 'Customer City'
		dataType: string
		lineageTag: 720be464-c4ea-4dd6-9162-304cab2fa89b
		summarizeBy: none
		sourceColumn: Customer City

		annotation SummarizationSetBy = Automatic

	column 'Customer Country'
		dataType: string
		lineageTag: fefe3ffb-489d-49bd-a89e-cfdc101e9e7a
		summarizeBy: none
		sourceColumn: Customer Country

		annotation SummarizationSetBy = Automatic

	column 'Customer Email'
		dataType: string
		lineageTag: 7efd3ae5-66e6-46bc-ab19-f7049f1f8575
		summarizeBy: none
		sourceColumn: Customer Email

		annotation SummarizationSetBy = Automatic

	column 'Customer Fname'
		dataType: string
		lineageTag: 755da8e1-6381-4b4b-a0b9-9f03b7cdd72b
		summarizeBy: none
		sourceColumn: Customer Fname

		annotation SummarizationSetBy = Automatic

	column 'Customer Id'
		dataType: int64
		formatString: 0
		lineageTag: 6eca1fc4-9f09-42fc-8f44-d391fbd1f052
		summarizeBy: count
		sourceColumn: Customer Id

		annotation SummarizationSetBy = Automatic

	column 'Customer Lname'
		dataType: string
		lineageTag: 5ffd4fb5-13da-4825-aa06-f0a65c75f8b0
		summarizeBy: none
		sourceColumn: Customer Lname

		annotation SummarizationSetBy = Automatic

	column 'Customer Password'
		dataType: string
		lineageTag: 87bdb862-b811-4c42-9468-9a813b799d61
		summarizeBy: none
		sourceColumn: Customer Password

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 78e256bf-b342-4bb2-a40f-079239f21ddc
		summarizeBy: none
		sourceColumn: Customer Segment

		annotation SummarizationSetBy = Automatic

	column 'Customer State'
		dataType: string
		lineageTag: 545dadd5-26db-47a8-bf64-dbcab7dedfc0
		summarizeBy: none
		sourceColumn: Customer State

		annotation SummarizationSetBy = Automatic

	column 'Customer Street'
		dataType: string
		lineageTag: 4ad07277-362c-45fa-8898-d4cdb6422423
		summarizeBy: none
		sourceColumn: Customer Street

		annotation SummarizationSetBy = Automatic

	column 'Customer Zipcode'
		dataType: int64
		formatString: 0
		lineageTag: a5da7f5d-e7a6-45c2-8b1b-ee7ec96629bc
		summarizeBy: sum
		sourceColumn: Customer Zipcode

		annotation SummarizationSetBy = Automatic

	column 'Department Id'
		dataType: int64
		formatString: 0
		lineageTag: 1710a99c-7c5d-4a31-b904-020c5803bc57
		summarizeBy: count
		sourceColumn: Department Id

		annotation SummarizationSetBy = Automatic

	column 'Department Name'
		dataType: string
		lineageTag: 9368359c-3b8d-4aa4-ae2b-556ce1d58195
		summarizeBy: none
		sourceColumn: Department Name

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: c4d0d44a-322e-4f1f-a22a-7d9646187c26
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 06e789db-55f9-45e9-9d03-577c89d8dd94
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Market
		dataType: string
		lineageTag: 1b47212f-5a03-4950-a3a7-6ae33d14b22f
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column 'Order City'
		dataType: string
		lineageTag: f57767a8-6169-48b9-968e-f0b441d66e55
		summarizeBy: none
		sourceColumn: Order City

		annotation SummarizationSetBy = Automatic

	column 'Order Country'
		dataType: string
		lineageTag: da934610-0c50-4dff-9559-b127494aed67
		summarizeBy: none
		sourceColumn: Order Country

		annotation SummarizationSetBy = Automatic

	column 'Order Customer Id'
		dataType: int64
		formatString: 0
		lineageTag: 91119bce-e742-4bd3-aee8-46dfc8be7bee
		summarizeBy: count
		sourceColumn: Order Customer Id

		annotation SummarizationSetBy = Automatic

	column 'order date (DateOrders)'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5202a045-bccd-4974-b3d8-932122b914db
		summarizeBy: none
		sourceColumn: order date (DateOrders)

		variation Variation
			isDefault
			relationship: 692baf81-a502-47f8-b326-7dc8877b4e23
			defaultHierarchy: LocalDateTable_de9532e8-a608-4b8b-abf1-f07994a619cf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Order Id'
		dataType: int64
		formatString: 0
		lineageTag: 63ed0114-48b8-4c1a-872b-1597ed4d4a0c
		summarizeBy: count
		sourceColumn: Order Id

		annotation SummarizationSetBy = Automatic

	column 'Order Item Cardprod Id'
		dataType: int64
		formatString: 0
		lineageTag: 5dcbaa3e-f893-4cb3-9b5e-33741dc8155b
		summarizeBy: count
		sourceColumn: Order Item Cardprod Id

		annotation SummarizationSetBy = Automatic

	column 'Order Item Discount'
		dataType: double
		lineageTag: 7a9bfee3-e92c-4190-9fc5-38df050a88f6
		summarizeBy: sum
		sourceColumn: Order Item Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Item Discount Rate'
		dataType: double
		lineageTag: 95dbd8d0-7127-441b-a0cd-1aecab7eb1f4
		summarizeBy: sum
		sourceColumn: Order Item Discount Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Item Id'
		dataType: int64
		formatString: 0
		lineageTag: f2343ef1-c128-41be-a632-90736b89a14a
		summarizeBy: count
		sourceColumn: Order Item Id

		annotation SummarizationSetBy = Automatic

	column 'Order Item Product Price'
		dataType: double
		lineageTag: ab933eb8-a38b-4b12-bbc4-8eb1ad8021f5
		summarizeBy: sum
		sourceColumn: Order Item Product Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Item Profit Ratio'
		dataType: double
		lineageTag: ab8f5212-0a5f-4f60-b497-017d23ad59f0
		summarizeBy: sum
		sourceColumn: Order Item Profit Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Item Quantity'
		dataType: int64
		formatString: 0
		lineageTag: b2a5a5eb-75ed-4b37-991b-72f063bb8238
		summarizeBy: sum
		sourceColumn: Order Item Quantity

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: c86ff293-dc37-4b21-9699-d235ae0bf9c1
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Item Total'
		dataType: double
		lineageTag: b57a4b33-2386-4a11-8a9a-50c075aa37b8
		summarizeBy: sum
		sourceColumn: Order Item Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Profit Per Order'
		dataType: double
		lineageTag: db3602c1-26c5-432c-8433-7cec4287f149
		summarizeBy: sum
		sourceColumn: Order Profit Per Order

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Region'
		dataType: string
		lineageTag: b1ecc64c-1157-45b7-b015-94323ad91111
		summarizeBy: none
		sourceColumn: Order Region

		annotation SummarizationSetBy = Automatic

	column 'Order State'
		dataType: string
		lineageTag: c454e1da-2d0f-416a-b59d-0c8baa6cc91e
		summarizeBy: none
		sourceColumn: Order State

		annotation SummarizationSetBy = Automatic

	column 'Order Status'
		dataType: string
		lineageTag: 536c8b72-5b48-4ce6-9e9d-43637ca22e1e
		summarizeBy: none
		sourceColumn: Order Status

		annotation SummarizationSetBy = Automatic

	column 'Order Zipcode'
		dataType: int64
		formatString: 0
		lineageTag: 502ad120-855c-4092-86cf-6118de0c3976
		summarizeBy: sum
		sourceColumn: Order Zipcode

		annotation SummarizationSetBy = Automatic

	column 'Product Card Id'
		dataType: int64
		formatString: 0
		lineageTag: e786954d-15d2-4b34-88ea-20a5101e5b6c
		summarizeBy: count
		sourceColumn: Product Card Id

		annotation SummarizationSetBy = Automatic

	column 'Product Category Id'
		dataType: int64
		formatString: 0
		lineageTag: 53258c81-aa73-4e21-bbb2-7058a9d59141
		summarizeBy: count
		sourceColumn: Product Category Id

		annotation SummarizationSetBy = Automatic

	column 'Product Description'
		dataType: string
		lineageTag: 8bb85dd6-2ddd-490a-8b59-423a6311dd7c
		summarizeBy: none
		sourceColumn: Product Description

		annotation SummarizationSetBy = Automatic

	column 'Product Image'
		dataType: string
		lineageTag: f39373dc-4feb-4b22-a772-176c307cd220
		summarizeBy: none
		sourceColumn: Product Image

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 72a327d8-59b9-4512-99d4-8452dd7dc06c
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Product Price'
		dataType: double
		lineageTag: c9a4cfa7-890a-4df1-b71b-a89789f74a7c
		summarizeBy: sum
		sourceColumn: Product Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Product Status'
		dataType: int64
		formatString: 0
		lineageTag: 937f9c67-4041-4504-a7b5-c9eb8560cd37
		summarizeBy: sum
		sourceColumn: Product Status

		annotation SummarizationSetBy = Automatic

	column 'shipping date (DateOrders)'
		dataType: string
		lineageTag: 65220f50-cf65-4f6f-80f3-58fb7ee88630
		summarizeBy: none
		sourceColumn: shipping date (DateOrders)

		annotation SummarizationSetBy = Automatic

	column 'Shipping Mode'
		dataType: string
		lineageTag: 3485fdad-dc62-4249-8631-871eedd74898
		summarizeBy: none
		sourceColumn: Shipping Mode

		annotation SummarizationSetBy = Automatic

	column 'Delivery Difference Days' =
			
			'DataCoSupplyChain Dataset'[Days for shipping (real)]
			    - 'DataCoSupplyChain Dataset'[Days for shipment (scheduled)]]
		formatString: 0
		lineageTag: 1c443c81-d503-4683-816a-09f3fcb60b92
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Delivery Timing' =
			
			VAR DaysDifference = 'DataCoSupplyChain Dataset'[Delivery Difference Days]
			RETURN
			    SWITCH(
			        TRUE(),
			        'DataCoSupplyChain Dataset'[Delivery Status] = "Shipping canceled", "Cancelled",
			        DaysDifference < 0,
			            FORMAT(ABS(DaysDifference), "0") & " day(s) early",
			        DaysDifference = 0, "On time",
			        FORMAT(DaysDifference, "0") & " day(s) late"
			    )
		lineageTag: fb7a2204-ea5f-4ff2-a711-38b55979a352
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Delivery Timing Sort' =
			
			IF(
			    'DataCoSupplyChain Dataset'[Delivery Status] = "Shipping canceled",
			    99,
			    'DataCoSupplyChain Dataset'[Delivery Difference Days]
			)
		formatString: 0
		lineageTag: 3b99e9cc-c644-4136-8ae5-e51188ad53ee
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Sales Month' =
			
			FORMAT(
			    'DataCoSupplyChain Dataset'[order date (DateOrders)],
			    "MMM yyyy"
			)
		lineageTag: 7be420c1-eb31-43cb-86c0-d48a953c49d8
		summarizeBy: none
		sortByColumn: 'Sales Month Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Sales Month Sort' =
			
			YEAR('DataCoSupplyChain Dataset'[order date (DateOrders)]) * 100
			    + MONTH('DataCoSupplyChain Dataset'[order date (DateOrders)])
		formatString: 0
		lineageTag: b4a83078-e769-49f4-aeda-c615c96c1d31
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Sales Month Label' =
			
			FORMAT(
			    'DataCoSupplyChain Dataset'[order date (DateOrders)],
			    "MMM yyyy"
			)
		lineageTag: 1ff7dbfd-47bb-4ad7-8ff5-8dd74f550c2e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Sales Month ' =
			
			YEAR('DataCoSupplyChain Dataset'[order date (DateOrders)]) * 100
			    + MONTH('DataCoSupplyChain Dataset'[order date (DateOrders)])
		formatString: 0
		lineageTag: 7e8f9295-3726-4664-9c72-31a098eb99d6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Sales Month Order' =
			
			YEAR('DataCoSupplyChain Dataset'[order date (DateOrders)]) * 100
			    + MONTH('DataCoSupplyChain Dataset'[order date (DateOrders)])
		formatString: 0
		lineageTag: fadb2b6e-b87e-40fa-a3b0-2a483ec489c8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Month Year Text' =
			
			FORMAT(
			    'DataCoSupplyChain Dataset'[order date (DateOrders)],
			    "MMM yyyy"
			)
		dataType: dateTime
		formatString: General Date
		lineageTag: 2ddf5103-e365-4e48-9ed3-7fa8a7ecc011
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 1025df6d-6838-4cc7-b3d2-df00296689a9
			defaultHierarchy: LocalDateTable_9d10335e-f769-4eaf-84e1-2b91c4ccf76c.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition 'DataCoSupplyChain Dataset' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\aspirevista\Downloads\DataCoSupplyChain Dataset.csv"),[Delimiter=",", Columns=53, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Type", type text}, {"Days for shipping (real)", Int64.Type}, {"Days for shipment (scheduled)", Int64.Type}, {"Benefit per order", type number}, {"Sales per customer", type number}, {"Delivery Status", type text}, {"Late_delivery_risk", Int64.Type}, {"Category Id", Int64.Type}, {"Category Name", type text}, {"Customer City", type text}, {"Customer Country", type text}, {"Customer Email", type text}, {"Customer Fname", type text}, {"Customer Id", Int64.Type}, {"Customer Lname", type text}, {"Customer Password", type text}, {"Customer Segment", type text}, {"Customer State", type text}, {"Customer Street", type text}, {"Customer Zipcode", Int64.Type}, {"Department Id", Int64.Type}, {"Department Name", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Market", type text}, {"Order City", type text}, {"Order Country", type text}, {"Order Customer Id", Int64.Type}, {"order date (DateOrders)", type text}, {"Order Id", Int64.Type}, {"Order Item Cardprod Id", Int64.Type}, {"Order Item Discount", type number}, {"Order Item Discount Rate", type number}, {"Order Item Id", Int64.Type}, {"Order Item Product Price", type number}, {"Order Item Profit Ratio", type number}, {"Order Item Quantity", Int64.Type}, {"Sales", type number}, {"Order Item Total", type number}, {"Order Profit Per Order", type number}, {"Order Region", type text}, {"Order State", type text}, {"Order Status", type text}, {"Order Zipcode", Int64.Type}, {"Product Card Id", Int64.Type}, {"Product Category Id", Int64.Type}, {"Product Description", type text}, {"Product Image", type text}, {"Product Name", type text}, {"Product Price", type number}, {"Product Status", Int64.Type}, {"shipping date (DateOrders)", type text}, {"Shipping Mode", type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(
				    #"Changed Type",
				    {{"order date (DateOrders)", type datetime}},
				    "en-US"
				)
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

